apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      volumes:
        - name: grafana-provisioning-datasources
          configMap:
            name: grafana-provisioning-datasources
      containers:
        - name: grafana
          image: grafana/grafana:6.1.6
          ports:
            - protocol: TCP
              containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: password
          volumeMounts:
            - name: grafana-provisioning-datasources
              mountPath: /etc/grafana/provisioning/datasources
        - name: sensu-agent
          image: sensu/sensu:5.9.0
          command: ["/opt/sensu/bin/sensu-agent", "start", "--log-level", "debug"]
          env:
            - name: SENSU_BACKEND_URL
              value: ws://sensu.default.svc.cluster.local:8081
            - name: SENSU_NAMESPACE
              value: demo
            - name: SENSU_SUBSCRIPTIONS
              value: grafana
            - name: SENSU_DEREGISTER
              value: "true"
            - name: SENSU_STATSD_EVENT_HANDLERS
              value: statsd

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
    - name: webui
      protocol: TCP
      port: 3001
      targetPort: 3000
