apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sensu
  namespace: default
spec:
  selector:
    matchLabels:
      app: sensu
  serviceName: "sensu"
  replicas: 3
  template:
    metadata:
      labels:
        app: sensu
    spec:
      containers:
        - name: backend
          image: sensu/sensu:5.9.0
          command: ["/opt/sensu/bin/sensu-backend", "start",
          "--log-level", "debug", "--etcd-name", "$(POD_NAME)",
          "--etcd-initial-advertise-peer-urls",
          "http://$(POD_NAME).sensu.default.svc.cluster.local:2380",
          "--etcd-listen-peer-urls",
          "http://0.0.0.0:2380",
          "--etcd-listen-client-urls",
          "http://0.0.0.0:2379",
          "--etcd-advertise-client-urls",
          "http://$(POD_NAME).sensu.default.svc.cluster.local:2379",
          "--etcd-initial-cluster-token", "",
          "--etcd-initial-cluster-state", "new",
          "--etcd-initial-cluster", "sensu-0=http://sensu-0.sensu.default.svc.cluster.local:2380,sensu-1=http://sensu-1.sensu.default.svc.cluster.local:2380,sensu-2=http://sensu-2.sensu.default.svc.cluster.local:2380"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - protocol: TCP
              containerPort: 8080
            - protocol: TCP
              containerPort: 8081
            - protocol: TCP
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sensu
  namespace: default
spec:
  selector:
    app: sensu
  type: LoadBalancer
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: ws
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: webui
      protocol: TCP
      port: 3000
      targetPort: 3000
