api_version: core/v2
type: Handler
metadata:
  namespace: demo
  name: influxdb
spec:
  type: pipe
  runtime_assets:
  - sensu-influxdb-handler
  command: sensu-influxdb-handler -a 'http://influxdb.default.svc.cluster.local:8086' -d sensu -u sensu -p password
  timeout: 10
  filters:
  - has_metrics
