apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:5.1.3
          ports:
            - protocol: TCP
              containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: password
        - name: sensu-agent
          image: sensu/sensu:2.0.0-beta.3
          command: ["/opt/sensu/bin/sensu-agent", "start", "--log-level", "debug"]
          env:
            - name: SENSU_BACKEND_URL
              value: ws://sensu-backend.default.svc.cluster.local:8081
            - name: SENSU_ORGANIZATION
              value: acme
            - name: SENSU_ENVIRONMENT
              value: demo
            - name: SENSU_SUBSCRIPTIONS
              value: grafana
            - name: SENSU_DEREGISTER
              value: "true"
            - name: SENSU_STATSD_EVENT_HANDLERS
              value: statsd
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  ports:
    - name: webui
      protocol: TCP
      port: 3001
      targetPort: 3000
